#!/bin/bash

git cherry -v main $(git rev-parse --abbrev-ref HEAD) | while read p; do
  commit_id=${p:2:40}
  msg="* "
  msg+=$(git rev-list --format=%B --max-count=1 $commit_id)
  msg=$(sed /^$/d <<< "$msg")
  msg+=$'\n'

  echo "$msg"
done
